server:
  port: 8082

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: validate
  liquibase:
#    enabled: false
    enabled: true
    change-log: classpath:db/migration/changelog-main.yaml

jwt:
  secret: sheeesh
  accessToken:
    lifetime: 1h
  refreshToken:
    lifetime: 1d