CREATE TABLE user_dto
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255)   NOT NULL,
    last_name  VARCHAR(255)   NOT NULL,
    email      VARCHAR(255)   NOT NULL UNIQUE,
    balance    DECIMAL(19, 2) NOT NULL
);


CREATE TABLE booking
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT         NOT NULL,
    apartment_id  BIGINT         NOT NULL,
    start_date    DATE           NOT NULL,
    end_date      DATE           NOT NULL,
    price_per_day DECIMAL(19, 2) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user_dto (id),
    FOREIGN KEY (apartment_id) REFERENCES apartments (id)
);
