CREATE TABLE users
(
    id         serial
        PRIMARY KEY,
    first_name VARCHAR(50),
    last_name  VARCHAR(50),
    email      VARCHAR(100) UNIQUE,
    balance    NUMERIC(10, 2) NOT NULL
);

CREATE TABLE booking
(
    end_date      DATE,
    price_per_day NUMERIC(38, 2),
    start_date    DATE,
    apartment_id  BIGINT UNIQUE
        CONSTRAINT fknn32oiv6ykrusjq87xuccx2lg
            REFERENCES apartments,
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
