server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  accessToken:
    lifetime: ${JWT_ACCESS_TOKEN_LIFETIME:1h}
  refreshToken:
    lifetime: ${JWT_REFRESH_TOKEN_LIFETIME:1d}

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: auth_route
          uri: ${AUTH_URI:http://localhost:8081}
          predicates:
            - Path=${AUTH_PATH:/v1/api/auth/**}
        - id: user_route
          uri: ${USER_URI:http://localhost:8081}
          predicates:
            - Path=${USER_PATH:/v1/api/users/**}
        - id: booking_route
          uri: ${BOOKING_URI:http://localhost:8082}
          predicates:
            - Path=${BOOKING_PATH:/v1/api/booking/**}
        - id: apartment_route
          uri: ${APARTMENT_URI:http://localhost:8082}
          predicates:
            - Path=${APARTMENT_PATH:/v1/api/apartment/**}
