CREATE TABLE users
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name    VARCHAR(255)   NOT NULL,
    last_name     VARCHAR(255)   NOT NULL,
    email         VARCHAR(255)   NOT NULL UNIQUE,
    password      VARCHAR(255)   NOT NULL,
    phone_number  VARCHAR(255)   NOT NULL UNIQUE,
    balance       DECIMAL(19, 2) NOT NULL,
    refresh_token VARCHAR(255),
    role_id       BIGINT         NOT NULL,
    role          VARCHAR(20)    NOT NULL
);

CREATE TABLE roles
(
    id   SERIAL PRIMARY KEY,
    role VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO roles (role)
VALUES ('ROLE_USER'),
       ('ROLE_ADMIN'),
       ('ROLE_EDITOR');
