server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: validate
  liquibase:
    enabled: true
#    enabled: false
    change-log: classpath:db/migration/changelog-main.yaml

jwt:
  secret: sheeesh
  accessToken:
    lifetime: 1h
  refreshToken:
    lifetime: 1d