FROM openjdk:22-slim AS build

RUN apt-get update && apt-get install -y maven

COPY . .
RUN mvn clean package

FROM eclipse-temurin:22-jre-jammy

COPY --from=build /target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
